<?php

namespace Inowas\Flopy\Tests\Model\Package;

use Inowas\Flopy\Model\Package\BasPackage;

class BasPackageTest extends \PHPUnit_Framework_TestCase
{
    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testInstantiate() {
        $bas = new BasPackage();
        $this->assertInstanceOf(BasPackage::class, $bas);
    }

    public function testDisPackageHasJsonSerializeImplementedAndReturnsJson() {
        $bas = new BasPackage();
        $this->assertJson(json_encode($bas));
    }

    public function testBasPackageProperties() {
        $bas = new BasPackage();
        $json = json_encode($bas);
        $basObj = json_decode($json);
        $this->assertObjectHasAttribute('ibound', $basObj);
        $this->assertObjectHasAttribute('strt', $basObj);
        $this->assertObjectHasAttribute('ifrefm', $basObj);
        $this->assertObjectHasAttribute('ixsec', $basObj);
        $this->assertObjectHasAttribute('ichflg', $basObj);
        $this->assertObjectHasAttribute('stoper', $basObj);
        $this->assertObjectHasAttribute('hnoflo', $basObj);
        $this->assertObjectHasAttribute('extension', $basObj);
        $this->assertObjectHasAttribute('unitnumber', $basObj);
    }
}
