<?php

namespace Inowas\PyprocessingBundle\Tests\Model\Modflow\Package;


use Inowas\PyprocessingBundle\Model\Modflow\Package\MfPackage;

class MfPackageTest extends \PHPUnit_Framework_TestCase
{
    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testInstantiate() {
        $mf = new MfPackage('A', 'B', 'C', 'D');
        $this->assertInstanceOf(MfPackage::class, $mf);
    }

    public function testDisPackageHasJsonSerializeImplementedAndReturnsJson() {
        $mf = new MfPackage('A', 'B', 'C', 'D');
        $this->assertJson(json_encode($mf));
    }

    public function testBasPackageProperties() {
        $mf = new MfPackage('A', 'B', 'C', 'D');
        $json = json_encode($mf);
        $mfObj = json_decode($json);
        $this->assertObjectHasAttribute('modelname', $mfObj);
        $this->assertObjectHasAttribute('namefile_ext', $mfObj);
        $this->assertObjectHasAttribute('version', $mfObj);
        $this->assertObjectHasAttribute('exe_name', $mfObj);
        $this->assertObjectHasAttribute('structured', $mfObj);
        $this->assertObjectHasAttribute('listunit', $mfObj);
        $this->assertObjectHasAttribute('model_ws', $mfObj);
        $this->assertObjectHasAttribute('external_path', $mfObj);
        $this->assertObjectHasAttribute('verbose', $mfObj);
    }
}
