<?php

namespace AppBundle\Repository;

/**
 * CalculationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculationRepository extends \Doctrine\ORM\EntityRepository
{
}
