<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GeologicalLayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeologicalLayerRepository extends EntityRepository
{
}

