<?php

namespace AppBundle\Repository;

/**
 * ModFlowInitialValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModFlowInitialValueRepository extends \Doctrine\ORM\EntityRepository
{
}
