<?php

namespace AppBundle\Repository;

/**
 * ModFlowInitialValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModFlowModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLayerId($soilModelId)
    {
        $query = $this->createQueryBuilder('mfm')
            ->leftJoin('mfm.soilModel', 'sm')
            ->where('sm.id = :id')
            ->setParameter('id', $soilModelId)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
