<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ConstantHeadBoundary;
use AppBundle\Entity\GeneralHeadBoundary;
use AppBundle\Entity\ModelObject;
use AppBundle\Entity\ObservationPoint;
use AppBundle\Entity\StreamBoundary;
use AppBundle\Model\BoundingBox;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ModFlowInitialValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModFlowModelRepository extends EntityRepository
{
    public function findByLayerId($soilModelId)
    {
        $query = $this->createQueryBuilder('mfm')
            ->leftJoin('mfm.soilModel', 'sm')
            ->where('sm.id = :id')
            ->setParameter('id', $soilModelId)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    public function transformBoundingBox(BoundingBox $boundingBox, $targetSrid)
    {
        $query = $this->getEntityManager()
            ->getConnection()
            ->prepare(sprintf('SELECT ST_AsGeoJson(ST_Transform(ST_GeomFromText(\'POINT(%s %s)\' , %s), %s))',
                $boundingBox->getXMin(),
                $boundingBox->getYMin(),
                $boundingBox->getSrid(),
                $targetSrid
                ))
        ;

        $query->execute();
        $lowerLeft = json_decode($query->fetchAll()[0]['st_asgeojson']);

        $query = $this->getEntityManager()
            ->getConnection()
            ->prepare(sprintf('SELECT ST_AsGeoJson(ST_Transform(ST_GeomFromText(\'POINT(%s %s)\' , %s), %s))',
                $boundingBox->getXMax(),
                $boundingBox->getYMax(),
                $boundingBox->getSrid(),
                $targetSrid
            ))
        ;

        $query->execute();
        $upperRight = json_decode($query->fetchAll()[0]['st_asgeojson']);

        $bb = new BoundingBox();
        $bb->setXMin($lowerLeft->coordinates[0]);
        $bb->setYMin($lowerLeft->coordinates[1]);
        $bb->setXMax($upperRight->coordinates[0]);
        $bb->setYMax($upperRight->coordinates[1]);
        $bb->setSrid($targetSrid);

        return $bb;
    }

    public function getGeometryFromModelObjectAsGeoJSON(ModelObject $mo, $targetSrid)
    {
        $id = $mo->getId()->toString();

        if ($mo instanceof ConstantHeadBoundary)
        {
            $query = $this->getEntityManager()
                ->createQuery('SELECT ST_AsGeoJson(ST_Transform(a.geometry, :srid)) FROM AppBundle:ConstantHeadBoundary a WHERE a.id = :id')
                ->setParameter('id', $id)
                ->setParameter('srid', $targetSrid)
            ;

            return $query->getSingleScalarResult();
        }

        if ($mo instanceof GeneralHeadBoundary)
        {
            $query = $this->getEntityManager()
                ->createQuery('SELECT ST_AsGeoJson(ST_Transform(a.geometry, :srid)) FROM AppBundle:GeneralHeadBoundary a WHERE a.id = :id')
                ->setParameter('id', $id)
                ->setParameter('srid', $targetSrid)
            ;

            return $query->getSingleScalarResult();
        }

        if ($mo instanceof ObservationPoint)
        {
            $query = $this->getEntityManager()
                ->createQuery('SELECT ST_AsGeoJson(ST_Transform(a.geometry, :srid)) FROM AppBundle:ObservationPoint a WHERE a.id = :id')
                ->setParameter('id', $id)
                ->setParameter('srid', $targetSrid)
            ;

            return $query->getSingleScalarResult();
        }

        if ($mo instanceof StreamBoundary)
        {
            $query = $this->getEntityManager()
                ->createQuery('SELECT ST_AsGeoJson(ST_Transform(a.geometry, :srid)) FROM AppBundle:Stream a WHERE a.id = :id')
                ->setParameter('id', $id)
                ->setParameter('srid', $targetSrid)
            ;

            return $query->getSingleScalarResult();
        }

        return null;
    }
}
