<?php

namespace AppBundle\Repository;

/**
 * SoilModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoilModelRepository extends \Doctrine\ORM\EntityRepository
{
}
