<?php

namespace AppBundle\Repository;

/**
 * stressPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stressPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
