<?php

namespace AppBundle\Repository;

/**
 * ToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolRepository extends \Doctrine\ORM\EntityRepository
{
}
