<?php

namespace Inowas\Flopy\Tests\Model\ValueObject;

use Inowas\Flopy\Model\ValueObject\StressPeriodOutputControl;

class StressPeriodOutputControlTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreate(){
        $spoc = StressPeriodOutputControl::create(0,0,StressPeriodOutputControl::SAVE_HEAD);
        $this->assertInstanceOf(StressPeriodOutputControl::class, $spoc);
    }

    public function testSerialize(){
        $spoc = StressPeriodOutputControl::create(5,6,StressPeriodOutputControl::SAVE_HEAD);
        $this->assertJson(json_encode($spoc));
        $response = json_decode(json_encode($spoc));

        $this->assertObjectHasAttribute('stressPeriod', $response);
        $this->assertEquals(5, $response->stressPeriod);
        $this->assertObjectHasAttribute('timeStep', $response);
        $this->assertEquals(6, $response->timeStep);
        $this->assertObjectHasAttribute('type', $response);
        $this->assertEquals('SAVE HEAD', $response->type);
    }

    public function testSerializeArray(){
        $spocs = array();
        $spocs[] = StressPeriodOutputControl::create(5,6,StressPeriodOutputControl::SAVE_HEAD);
        $spocs[] = StressPeriodOutputControl::create(5,7,StressPeriodOutputControl::SAVE_HEAD);
        $spocs[] = StressPeriodOutputControl::create(5,8,StressPeriodOutputControl::SAVE_HEAD);
        $spocs[] = StressPeriodOutputControl::create(6,1,StressPeriodOutputControl::SAVE_HEAD);
        $spocs[] = StressPeriodOutputControl::create(6,2,StressPeriodOutputControl::SAVE_HEAD);
        $this->assertJson(json_encode($spocs));
        $response = json_decode(json_encode($spocs));
        $this->assertCount(5, $response);
        $this->assertObjectHasAttribute('stressPeriod', $response[0]);
        $this->assertEquals(5, $response[0]->stressPeriod);
        $this->assertObjectHasAttribute('timeStep', $response[0]);
        $this->assertEquals(6, $response[0]->timeStep);
        $this->assertObjectHasAttribute('type', $response[0]);
        $this->assertEquals('SAVE HEAD', $response[0]->type);
    }

}
