<?php

namespace AppBundle\Entity;

use AppBundle\Model\Raster as RasterObject;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * RasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RasterRepository extends EntityRepository
{

    /**
     * @param Raster $raster
     * @return bool
     * @throws \Doctrine\DBAL\DBALException
     */
    public function setEmptyRaster(Raster $raster)
    {
        /** @var RasterObject $rasterObj */
        $rasterObj = $raster->getRaster();

        $tableName = $this->getEntityManager()->getClassMetadata('AppBundle:Raster')->getTableName();

        $sql = "
            UPDATE ".$tableName."
            SET rast = ST_MakeEmptyRaster(
                ".$rasterObj->getWidth().",
                ".$rasterObj->getHeight().",
                ".$rasterObj->getUpperLeftX().",
                ".$rasterObj->getUpperLeftY().",
                ".$rasterObj->getScaleX().",
                ".$rasterObj->getScaleY().",
                ".$rasterObj->getSkewX().",
                ".$rasterObj->getSkewY().",
                ".$rasterObj->getSrid()."
            )
            WHERE id = ".$raster->getId()."
        ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //return $stmt->fetchAll();
        return true;
    }

    /**
     * @param Raster $raster
     * @return bool
     * @throws \Doctrine\DBAL\DBALException
     */
    public function setEmptyRasterAndAddBand(Raster $raster)
    {
        /** @var RasterObject $rasterObj */
        $rasterObj = $raster->getRaster();
        $tableName = $this->getEntityManager()->getClassMetadata('AppBundle:Raster')->getTableName();

        $this->setEmptyRaster($raster);

        $sql = "
            UPDATE ".$tableName."
            SET rast = st_addband(
                rast,
                ARRAY[
	            	ROW(
	            	    ".$rasterObj->getBand()->getId().",
                        ".$rasterObj->getBand()->getPixelType().",
                        ".$rasterObj->getBand()->getInitValue().",
                        ".$rasterObj->getBand()->getNoDataVal()."
                    )
			    ]::addbandarg[]
            )
            WHERE id = ".$raster->getId()."
        ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //return $stmt->fetchAll();
        return true;
    }

    /**
     * @param Raster $raster
     * @return bool
     * @throws \Doctrine\DBAL\DBALException
     */
    public function addRasterWithData(Raster $raster)
    {
        /** @var RasterObject $rasterObj */
        $rasterObj = $raster->getRaster();

        $tableName = $this->getEntityManager()
            ->getClassMetadata('AppBundle:Raster')
            ->getTableName();

        $this->setEmptyRasterAndAddBand($raster);

        $sql = "
            UPDATE ".$tableName."
            SET rast = ST_SetValues(
                rast,
                ".$rasterObj->getBand()->getId().",
                1,
                1,
                ".$this->conversionArrayToSQL($rasterObj->getBand()->getData())."
            )
            WHERE id = ".$raster->getId()."
        ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        //return $stmt->fetchAll();
        return true;
    }

    public function getValuesFromRaster($id)
    {
        $tableName = $this->getEntityManager()
            ->getClassMetadata('AppBundle:Raster')
            ->getTableName();

        $sql = "
            SELECT x, y, ST_VALUE(rast, 1, x, y) AS b1val
            FROM ".$tableName."
            CROSS JOIN generate_series(1, 1000) As x
            CROSS JOIN generate_series(1, 1000) As y
            WHERE id = ".$id."
            AND x <= ST_Width(rast) AND y <= ST_Height(rast);
        ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        $xyResults = $stmt->fetchAll();

        $data = array();
        foreach ($xyResults as $xyResult)
        {
            $data[$xyResult['y']-1][$xyResult['x']-1] = intval($xyResult['b1val']);
        }

        return $data;
    }

    /**
     * @param $sqlExpr
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function executePlainSQL($sqlExpr)
    {
        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlExpr);
        $stmt->execute();

        return $stmt->fetchAll();
    }

    /**
     * @param $sqlExpr
     * @return array
     */
    public function conversionTestDQL($sqlExpr)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT '.$sqlExpr.' FROM AppBundle\Entity\Raster');

        $result = $query->getResult();
        return $result;
    }

    /**
     * @param $rows
     * @return string
     */
    private function conversionArrayToSQL($rows)
    {
        //ARRAY[[9, 9], [9, 9]]::double precision[][]

        $value = "";

        if (is_array($rows))
        {
            $value .= 'ARRAY[';
            foreach ($rows as $row)
            {
                $value .= '[';
                $value .= sprintf('%s', implode(",", $row));
                $value .= '],';
            }
            $value = rtrim($value, ",");
            $value .= ']::double precision[][]';
        }
        return $value;
    }
}
